version: "3.8"

services:
  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:8001
      - GIG_SERVICE_URL=http://gig-service:8002
      - BOOKING_SERVICE_URL=http://booking-service:8003
      - PAYMENT_SERVICE_URL=http://payment-service:8004
      - MESSAGE_SERVICE_URL=http://message-service:8005
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - auth-service
      - gig-service
      - booking-service
      - payment-service
      - message-service
    networks:
      - microservices-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    volumes:
      - ./services/auth-service/serviceAccountKey.json:/app/serviceAccountKey.json
    networks:
      - microservices-network

  # Gig Service
  gig-service:
    build:
      context: ./services/gig-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://gig_user:gig123@gig-db:5432/gig_db
      - JWT_SECRET_KEY=4866529bc05efeff764d41b723921b2a
      - ALGORITHM=HS256
    depends_on:
      - gig-db
    networks:
      - microservices-network

  # Booking Service
  booking-service:
    build:
      context: ./services/booking-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - DATABASE_URL=postgresql://postgres:password@booking-db:5432/booking_db
    depends_on:
      - booking-db
    networks:
      - microservices-network

  # Payment Service
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
    networks:
      - microservices-network

  # Message Service
  message-service:
    build:
      context: ./services/msg-service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - MONGODB_URI=mongodb://message-db:27017/messages
    depends_on:
      - message-db
    networks:
      - microservices-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:8000
    depends_on:
      - api-gateway
    networks:
      - microservices-network

  # Databases
  gig-db:
    image: postgres:17
    environment:
      - POSTGRES_DB=gig_db
      - POSTGRES_USER=gig_user
      - POSTGRES_PASSWORD=gig123
    volumes:
      - gig_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  booking-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=booking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  message-db:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=messages
    volumes:
      - message_db_data:/data/db
    networks:
      - microservices-network

  # Redis for caching (optional)
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

volumes:
  gig_db_data:
  booking_db_data:
  message_db_data:
  redis_data:

networks:
  microservices-network:
    driver: bridge
