services:
  user-service:
    build: .
    ports:
      - "8006:8006"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
