services:
  review-db:
    # We will use the official PostgreSQL image, version 15.
    image: postgres:17

    # These environment variables configure PostgreSQL when it first starts.
    environment:
      - POSTGRES_USER=review
      - POSTGRES_PASSWORD=review123
      - POSTGRES_DB=review_db

    # This maps the port inside the Docker container (5432)
    # to a port on your local machine (5433). We use 5433 to avoid
    # conflicts with any other PostgreSQL you might have installed.
    ports:
      - "5437:5432"

    # This makes sure your data is saved even if you stop or remove
    # the container. Your data will be stored in a "volume" named 'postgres_data'.
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  review-service:
    build: .
    ports:
      - "8007:8007"
    depends_on:
      - review-db
    environment:
      - DATABASE_URL=postgresql://review:review123@review-db:5432/review_db

# This defines the named volume we used above.
volumes:
  postgres_data:
