"""Add thumbnail column to gigs table

Revision ID: 721e938a3996
Revises: a65640364fc0
Create Date: 2025-09-14 03:29:09.844598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721e938a3996'
down_revision: Union[str, Sequence[str], None] = 'a65640364fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gigs', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gigs', 'thumbnail_url')
    # ### end Alembic commands ###
