services:
  auth-service:
    ports:
      - "8001:8001"
  user-service:
    ports:
      - "8006:8006"
  gig-service:
    ports:
      - "8002:8002"
  booking-service:
    ports:
      - "8003:8003"
  payment-service:
    ports:
      - "8004:8004"
  review-service:
    ports:
      - "8007:8007"
  msg-service:
    ports:
      - "8005:8005"
  notification-service:
    ports:
      - "8008:8008"
  admin-service:
    ports:
      - "8009:8009"
  meeting-service:
    ports:
      - "8010:8007"
