version: '3.8'

services:
  admin-service:
    build: .
    container_name: hire_expert_admin
    env_file:
      - ./.env
    ports:
      - "8009:8009"
    volumes:
      - ./uploads:/app/uploads
      - ./:/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8009/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

