version: '3.8'

services:
  admin-service:
    build: .
    container_name: admin-service
    ports:
      - "8009:8009"
    environment:
      - HOST=0.0.0.0
      - PORT=8009
      - DEBUG=false
      - SERVICE_NAME=admin-service
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-models/gemini-2.5-flash}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - TOP_K_RESULTS=${TOP_K_RESULTS:-5}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - FAISS_INDEX_PATH=/app/data/faiss_index
      - VECTOR_DIMENSION=${VECTOR_DIMENSION:-384}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-10485760}
      - UPLOAD_DIR=/app/uploads
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hire-expert-network

networks:
  hire-expert-network:
    external: true

