version: '3.8'

services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hire-expert-booking-dev
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - USER_SERVICE_URL=http://host.docker.internal:8001
      - GIG_SERVICE_URL=http://host.docker.internal:8002
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002
    restart: unless-stopped
    command: python main.py
