services:
  # Booking service using external AWS RDS database
  booking-service:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8003
