version: "3"

services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8005:8000" # Map to port 8005 to avoid conflicts with other services
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - hire-an-expert-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - hire-an-expert-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq-data:
    driver: local

networks:
  hire-an-expert-network:
    name: hire-an-expert-network
    driver: bridge
    # Connect to the existing network if it exists
    external: true
