version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userservice # ← your database name
      POSTGRES_USER: userservice # ← your database user
      POSTGRES_PASSWORD: userservice # ← your database password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
